#!/usr/bin/env python3

import re
import sys
import urllib.request

SOURCE = 'https://raw.githubusercontent.com/raspberrypi/utils/master/pinctrl/{}'

MODELS = [
    ('bcm2835', 'Pi 1-3, Zero', 'Alt', 'gpiochip_bcm2835.c', 'bcm2835_gpio_alt_names', 6),
    ('bcm2711', 'Pi 4, 400, CM4', 'Alt', 'gpiochip_bcm2835.c', 'bcm2711_gpio_alt_names', 6),
    ('rp1', 'Pi 5', 'F', 'gpiochip_rp1.c', 'rp1_gpio_fsel_names', 9),
]

HEADER_GPIOS = 28

RULES = [
    (r'^SDA(\d)$', r'I2C\1 SDA'),
    (r'^SCL(\d)$', r'I2C\1 SCL'),
    (r'^TXD(\d)$', r'UART\1 TXD'),
    (r'^RXD(\d)$', r'UART\1 RXD'),
    (r'^CTS(\d)$', r'UART\1 CTS'),
    (r'^RTS(\d)$', r'UART\1 RTS'),
    (r'^DCD(\d)$', r'UART\1 DCD'),
    (r'^DSR(\d)$', r'UART\1 DSR'),
    (r'^DTR(\d)$', r'UART\1 DTR'),
    (r'^RI(\d)$', r'UART\1 RI'),
    (r'^SPI(\d)_CE(\d)_N$', r'SPI\1 CE\2'),
    (r'^SPI(\d)_CE(\d)$', r'SPI\1 CE\2'),
    (r'^SPI(\d)_(MISO|MOSI|SCLK)$', r'SPI\1 \2'),
    (r'^SPI(\d)_SIO(\d)$', r'SPI\1 SIO\2'),
    (r'^PCM_(CLK|FS|DIN|DOUT)$', r'PCM \1'),
    (r'^I2S(\d)_SCLK$', r'I2S\1 SCLK'),
    (r'^I2S(\d)_WS$', r'I2S\1 WS'),
    (r'^I2S(\d)_SDI(\d)$', r'I2S\1 SDI\2'),
    (r'^I2S(\d)_SDO(\d)$', r'I2S\1 SDO\2'),
    (r'^I2CSL_CE_N$', r'I2CSL CE'),
    (r'^I2CSL_SDI_MISO$', r'I2CSL MISO'),
    (r'^I2CSL_SDA_MOSI$', r'I2CSL SDA / MOSI'),
    (r'^I2CSL_SCL_SCLK$', r'I2CSL SCL / SCLK'),
    (r'^ARM_(TDI|TDO|TMS|TCK|TRST|RTCK)$', r'JTAG \1'),
    (r'^SA(\d+)$', r'SMI SA\1'),
    (r'^SD(\d+)$', r'SMI SD\1'),
    (r'^SOE_N_SE$', r'SMI SOE_N / SE'),
    (r'^SWE_N_SRW_N$', r'SMI SWE_N / SRW_N'),
    (r'^SD(\d)_(CLK|CMD)$', r'SD\1 \2'),
    (r'^SD(\d)_DAT(\d)$', r'SD\1 DAT\2'),
    (r'^PWM(\d)_(\d)$', r'PWM\1 CHAN\2'),
    (r'^PWM(\d)_CHAN(\d)$', r'PWM\1 CHAN\2'),
    (r'^LCD_(VSYNC|HSYNC)$', r'DPI \1'),
    (r'^PCLK$', r'DPI CLK'),
    (r'^DE$', r'DPI DEN'),
    (r'^MII_A_(.+)$', r'MII \1'),
    (r'^RGMII_(.+)$', r'RGMII \1'),
]


def normalise(name):
    for pattern, repl in RULES:
        if re.match(pattern, name):
            return re.sub(pattern, repl, name).replace('_', ' ')
    return name.replace('_', ' ')


def parse_table(source, symbol):
    start = source.index('{', source.index(symbol))
    depth = 0
    for end in range(start, len(source)):
        if source[end] == '{':
            depth += 1
        elif source[end] == '}':
            depth -= 1
            if depth == 0:
                break

    rows = []
    for row in re.findall(r'\{([^{}]*)\}', source[start + 1:end]):
        cells = [cell.strip() for cell in row.split(',') if cell.strip()]
        rows.append([None if cell == '0' else normalise(cell.strip('"')) for cell in cells])
    return rows


sources = {}
functions = {}

for model, name, prefix, filename, symbol, width in MODELS:
    if filename not in sources:
        sources[filename] = urllib.request.urlopen(SOURCE.format(filename)).read().decode('utf-8')

    table = parse_table(sources[filename], symbol)
    if len(table) < HEADER_GPIOS:
        sys.exit('{}: expected at least {} rows, got {}'.format(symbol, HEADER_GPIOS, len(table)))

    functions[model] = [(row + [None] * width)[:width] for row in table[:HEADER_GPIOS]]

with open('common/pin-functions.yaml', 'w') as f:
    f.write('# Generated by tools/pin-functions.py from raspberrypi/utils pinctrl\n')
    f.write('models:\n')
    for model, name, prefix, _, _, width in MODELS:
        f.write("- id: {}\n  name: '{}'\n  prefix: {}\n  width: {}\n".format(model, name, prefix, width))
    f.write('functions:\n')
    for model, _, _, _, _, _ in MODELS:
        f.write('  {}:\n'.format(model))
        for gpio, row in enumerate(functions[model]):
            cells = ', '.join("''" if cell is None else "'{}'".format(cell) for cell in row)
            f.write("    '{}': [{}]\n".format(gpio, cells))

print('common/pin-functions.yaml written')
