name: Pages

on:
  push:
    branches:
      - main

jobs:
  test:
    name: GitHub Pages (en)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Set up Python 3.11
        uses: actions/setup-python@v7
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          make deps

      - name: Build Packages
        run: |
          make site
          make -C api
          cp -r api/v1 output/site
          cp api/index.png output/site/v1/img/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./output/site
            cname: pinout.xyz
