name: QA

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  spelling:
    name: Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: pip install codespell

      - name: Check Spelling
        run: codespell
